[www]
listen = 127.0.0.1:9000
pm = ondemand
pm.max_children = 4
pm.process_idle_timeout = 30s
pm.max_requests = 200
clear_env = no
php_admin_value[error_log] = /data/data/com.termux/files/home/flexiqueue/storage/logs/php-fpm.log
php_admin_flag[log_errors] = on