<?php

namespace App\Services;

use App\Models\Program;
use App\Models\User;
use App\Support\SupervisorAuthResult;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;

/**
 * Authorization verifier for POST /api/public/display-settings (public, no auth).
 *
 * Supports the same auth_type matrix as supervisor override flows:
 * - preset_pin (public shape): supervisor/admin preset PIN for the active program (no supervisor_user_id)
 * - preset_qr: supervisor/admin preset QR token (persistent)
 * - temp_pin: temporary 6-digit code generated by supervisor/admin
 * - temp_qr: temporary QR scan token generated by supervisor/admin
 *
 * Program scoping is enforced at verification time: authorizer must be admin or supervisor of the active program.
 */
class PublicDisplaySettingsAuthService
{
    private const PRESET_PIN_FAIL_THROTTLE_PREFIX = 'public_display_settings:preset_pin_fail:';
    private const PRESET_PIN_FAIL_MAX_ATTEMPTS = 5;
    private const PRESET_PIN_FAIL_DECAY_MINUTES = 15;

    public function __construct(
        private PinService $pinService,
    ) {
    }

    /**
     * @param  array<string, mixed>  $validated
     */
    public function verify(array $validated, Program $program, Request $request): SupervisorAuthResult
    {
        $authType = $this->resolveAuthType($validated);
        // Simplified flow: no auth_type required; we infer based on provided pin or qr token and auto-detect.
        // Legacy flow: auth_type can still be provided.

        // Extra protection against brute-forcing preset PIN on a public endpoint.
        // We apply the limiter on PIN-based auth when we fall back to preset validation.
        // (Temp codes are high entropy and already bounded by TTL/uses.)
        if ($authType === 'preset_pin' || ($authType === null && ! empty($validated['pin']))) {
            $key = self::PRESET_PIN_FAIL_THROTTLE_PREFIX.$this->throttleKey($request);
            if (RateLimiter::tooManyAttempts($key, self::PRESET_PIN_FAIL_MAX_ATTEMPTS)) {
                return SupervisorAuthResult::failure('rate_limited');
            }
        }

        $verified = $this->verifyAutoDetect($validated, $authType, $program);

        if (! $verified) {
            if (in_array($authType, ['temp_pin', 'temp_qr'], true)) {
                return SupervisorAuthResult::failure('expired_temp');
            }

            if ($authType === 'preset_pin' || ($authType === null && ! empty($validated['pin']))) {
                RateLimiter::hit(
                    self::PRESET_PIN_FAIL_THROTTLE_PREFIX.$this->throttleKey($request),
                    self::PRESET_PIN_FAIL_DECAY_MINUTES * 60
                );
            }

            return SupervisorAuthResult::failure('invalid_pin');
        }

        if ($authType === 'preset_pin' || ($authType === null && ! empty($validated['pin']))) {
            RateLimiter::clear(self::PRESET_PIN_FAIL_THROTTLE_PREFIX.$this->throttleKey($request));
        }

        $authorizer = User::find((int) $verified['user_id']);
        if (! $authorizer || ! $this->canAuthorizeForProgram($authorizer, $program->id)) {
            return SupervisorAuthResult::failure('unauthorized_program');
        }

        return SupervisorAuthResult::success((int) $verified['user_id']);
    }

    /**
     * Auto-detect TEMP vs PRESET per spec:
     * - PIN: temp first, then preset (program-scoped)
     * - QR: temp first, then preset
     *
     * @param  array<string, mixed>  $validated
     * @return array{verified: true, user_id: int, role: string}|null
     */
    private function verifyAutoDetect(array $validated, ?string $authType, Program $program): ?array
    {
        // Legacy explicit auth_type support (kept for compatibility).
        if ($authType !== null) {
            if (! in_array($authType, ['preset_pin', 'preset_qr', 'temp_pin', 'temp_qr'], true)) {
                return null;
            }

            return match ($authType) {
                'temp_pin' => $this->pinService->validateTemporaryPin((string) ($validated['temp_code'] ?? '')),
                'temp_qr' => $this->pinService->validateTemporaryQr((string) ($validated['qr_scan_token'] ?? '')),
                'preset_qr' => $this->pinService->validatePresetQr((string) ($validated['qr_scan_token'] ?? '')),
                default => $this->pinService->validatePinForProgram($program->id, (string) ($validated['supervisor_pin'] ?? $validated['pin'] ?? '')),
            };
        }

        // Simplified contract: pin OR qr_scan_token.
        $pin = (string) ($validated['pin'] ?? '');
        if ($pin !== '') {
            $temp = $this->pinService->validateTemporaryPin($pin);
            if ($temp) return $temp;
            return $this->pinService->validatePinForProgram($program->id, $pin);
        }

        $qr = (string) ($validated['qr_scan_token'] ?? '');
        if ($qr !== '') {
            $temp = $this->pinService->validateTemporaryQr($qr);
            if ($temp) return $temp;
            return $this->pinService->validatePresetQr($qr);
        }

        return null;
    }

    /**
     * @param  array<string, mixed>  $validated
     */
    private function resolveAuthType(array $validated): ?string
    {
        $authType = $validated['auth_type'] ?? null;
        if ($authType && in_array($authType, ['preset_pin', 'preset_qr', 'temp_pin', 'temp_qr', 'pin', 'qr'], true)) {
            return $authType === 'pin' ? 'temp_pin' : ($authType === 'qr' ? 'temp_qr' : $authType);
        }

        // No explicit auth_type: use simplified auto-detect path.
        return null;
    }

    private function canAuthorizeForProgram(User $authorizer, int $programId): bool
    {
        if ($authorizer->isAdmin()) {
            return true;
        }

        return $authorizer->isSupervisorForProgram($programId);
    }

    private function throttleKey(Request $request): string
    {
        // Public endpoint: key by client IP (and a small UA slice) for stability across proxies.
        $ip = (string) ($request->ip() ?? 'unknown');
        $ua = (string) ($request->userAgent() ?? '');
        $ua = substr($ua, 0, 80);

        return sha1($ip.'|'.$ua);
    }
}

