<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\TemporaryAuthorization;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Per TRACK-OVERRIDES-REFACTOR §1.4: GET /api/auth/authorizations.
 * List recent generated authorizations for current user (creator).
 */
class AuthorizationsController extends Controller
{
    /**
     * List recent authorizations generated by current user.
     * Returns id, type, created_at, expires_at, used_at. No plaintext code.
     */
    public function index(Request $request): JsonResponse
    {
        $user = $request->user();

        $auths = TemporaryAuthorization::where('user_id', $user->id)
            ->orderByDesc('created_at')
            ->limit(20)
            ->get(['id', 'type', 'created_at', 'expires_at', 'used_at'])
            ->map(fn (TemporaryAuthorization $a) => [
                'id' => $a->id,
                'type' => $a->type,
                'created_at' => $a->created_at?->toIso8601String(),
                'expires_at' => $a->expires_at?->toIso8601String(),
                'used_at' => $a->used_at?->toIso8601String(),
            ])
            ->values()
            ->all();

        return response()->json(['authorizations' => $auths]);
    }
}
