<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Per docs/plans/PIN-QR-AUTHORIZATION-SYSTEM.md AUTH-1:
 * One-time authorization (Temporary PIN or Temporary QR) generated by supervisor.
 * type: pin|qr. Expires after use or TTL.
 */
class TemporaryAuthorization extends Model
{
    protected $fillable = [
        'user_id',
        'token_hash',
        'type',
        'expiry_mode',
        'max_uses',
        'used_count',
        'expires_at',
        'used_at',
        'last_used_at',
    ];

    protected function casts(): array
    {
        return [
            'expires_at' => 'datetime',
            'used_at' => 'datetime',
            'last_used_at' => 'datetime',
            'max_uses' => 'integer',
            'used_count' => 'integer',
        ];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function isExpired(): bool
    {
        return $this->expires_at && $this->expires_at->isPast();
    }

    public function isUsed(): bool
    {
        return $this->used_at !== null;
    }

    public function usesRemaining(): ?int
    {
        if ($this->max_uses === null) {
            return null;
        }

        return max(0, (int) $this->max_uses - (int) ($this->used_count ?? 0));
    }
}
